site_name: Brad Pitt
site_url: https://charlesreid1-toy-factory.github.io/brad-pitt/
repo_name: brad-pitt
repo_url: https://github.com/charlesreid1-toy-factory/brad-pitt
docs_dir: docs
edit_uri: ""
copyright: Copyright &copy; 2022 Chaz Reid

nav:
  - Index: index.md
  - Fight Club: fightclub.md
  - Interview with a Vampire: interview.md
  - Developers:
    - Release Process: release.md
    - API Reference: api.md

theme:
  name: material
  language: en
  icon:
    logo: material/alpha-b-circle
  favicon: material/alpha-b-circle
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - mkautodoc

plugins:
  - search:
      lang: en
  - mike:
      # These fields are all optional; the defaults are as below...
      canonical_version: null
      version_selector: true
      css_dir: css
